//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLogin.DataCenterServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datacenter", Namespace="http://www.turbine.com/SE/GLS")]
    [System.SerializableAttribute()]
    public partial class Datacenter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuickLogin.DataCenterServer.World[] WorldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LauncherConfigurationServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public QuickLogin.DataCenterServer.World[] Worlds {
            get {
                return this.WorldsField;
            }
            set {
                if ((object.ReferenceEquals(this.WorldsField, value) != true)) {
                    this.WorldsField = value;
                    this.RaisePropertyChanged("Worlds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AuthServer {
            get {
                return this.AuthServerField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthServerField, value) != true)) {
                    this.AuthServerField = value;
                    this.RaisePropertyChanged("AuthServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PatchServer {
            get {
                return this.PatchServerField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchServerField, value) != true)) {
                    this.PatchServerField = value;
                    this.RaisePropertyChanged("PatchServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LauncherConfigurationServer {
            get {
                return this.LauncherConfigurationServerField;
            }
            set {
                if ((object.ReferenceEquals(this.LauncherConfigurationServerField, value) != true)) {
                    this.LauncherConfigurationServerField = value;
                    this.RaisePropertyChanged("LauncherConfigurationServer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="World", Namespace="http://www.turbine.com/SE/GLS")]
    [System.SerializableAttribute()]
    public partial class World : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginServerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChatServerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusServerUrlField;
        
        private int OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LoginServerUrl {
            get {
                return this.LoginServerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginServerUrlField, value) != true)) {
                    this.LoginServerUrlField = value;
                    this.RaisePropertyChanged("LoginServerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ChatServerUrl {
            get {
                return this.ChatServerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatServerUrlField, value) != true)) {
                    this.ChatServerUrlField = value;
                    this.RaisePropertyChanged("ChatServerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StatusServerUrl {
            get {
                return this.StatusServerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusServerUrlField, value) != true)) {
                    this.StatusServerUrlField = value;
                    this.RaisePropertyChanged("StatusServerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusServerResult", Namespace="http://www.turbine.com/SE/GLS")]
    [System.SerializableAttribute()]
    public partial class StatusServerResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        private bool UpdatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Updating {
            get {
                return this.UpdatingField;
            }
            set {
                if ((this.UpdatingField.Equals(value) != true)) {
                    this.UpdatingField = value;
                    this.RaisePropertyChanged("Updating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="GLS Datacenter Info ServerSoap", Namespace="http://www.turbine.com/SE/GLS", ConfigurationName="DataCenterServer.GLSDatacenterInfoServerSoap")]
    public interface GLSDatacenterInfoServerSoap {
        
        // CODEGEN: 命名空间 http://www.turbine.com/SE/GLS 的元素名称 game 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/GetDatacenters", ReplyAction="*")]
        QuickLogin.DataCenterServer.GetDatacentersResponse GetDatacenters(QuickLogin.DataCenterServer.GetDatacentersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/GetDatacenters", ReplyAction="*")]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacentersResponse> GetDatacentersAsync(QuickLogin.DataCenterServer.GetDatacentersRequest request);
        
        // CODEGEN: 命名空间 http://www.turbine.com/SE/GLS 的元素名称 s 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/ServerInfo", ReplyAction="*")]
        QuickLogin.DataCenterServer.ServerInfoResponse ServerInfo(QuickLogin.DataCenterServer.ServerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/ServerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.ServerInfoResponse> ServerInfoAsync(QuickLogin.DataCenterServer.ServerInfoRequest request);
        
        // CODEGEN: 命名空间 http://www.turbine.com/SE/GLS 的元素名称 DumpCacheResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/DumpCache", ReplyAction="*")]
        QuickLogin.DataCenterServer.DumpCacheResponse DumpCache(QuickLogin.DataCenterServer.DumpCacheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/DumpCache", ReplyAction="*")]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.DumpCacheResponse> DumpCacheAsync(QuickLogin.DataCenterServer.DumpCacheRequest request);
        
        // CODEGEN: 命名空间 http://www.turbine.com/SE/GLS 的元素名称 game 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/GetDatacenterStatus", ReplyAction="*")]
        QuickLogin.DataCenterServer.GetDatacenterStatusResponse GetDatacenterStatus(QuickLogin.DataCenterServer.GetDatacenterStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/GetDatacenterStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacenterStatusResponse> GetDatacenterStatusAsync(QuickLogin.DataCenterServer.GetDatacenterStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatacentersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatacenters", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.GetDatacentersRequestBody Body;
        
        public GetDatacentersRequest() {
        }
        
        public GetDatacentersRequest(QuickLogin.DataCenterServer.GetDatacentersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GetDatacentersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string game;
        
        public GetDatacentersRequestBody() {
        }
        
        public GetDatacentersRequestBody(string game) {
            this.game = game;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatacentersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatacentersResponse", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.GetDatacentersResponseBody Body;
        
        public GetDatacentersResponse() {
        }
        
        public GetDatacentersResponse(QuickLogin.DataCenterServer.GetDatacentersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GetDatacentersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuickLogin.DataCenterServer.Datacenter[] GetDatacentersResult;
        
        public GetDatacentersResponseBody() {
        }
        
        public GetDatacentersResponseBody(QuickLogin.DataCenterServer.Datacenter[] GetDatacentersResult) {
            this.GetDatacentersResult = GetDatacentersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServerInfo", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.ServerInfoRequestBody Body;
        
        public ServerInfoRequest() {
        }
        
        public ServerInfoRequest(QuickLogin.DataCenterServer.ServerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class ServerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public ServerInfoRequestBody() {
        }
        
        public ServerInfoRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServerInfoResponse", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.ServerInfoResponseBody Body;
        
        public ServerInfoResponse() {
        }
        
        public ServerInfoResponse(QuickLogin.DataCenterServer.ServerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class ServerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ServerInfoResult;
        
        public ServerInfoResponseBody() {
        }
        
        public ServerInfoResponseBody(string ServerInfoResult) {
            this.ServerInfoResult = ServerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DumpCacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DumpCache", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.DumpCacheRequestBody Body;
        
        public DumpCacheRequest() {
        }
        
        public DumpCacheRequest(QuickLogin.DataCenterServer.DumpCacheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DumpCacheRequestBody {
        
        public DumpCacheRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DumpCacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DumpCacheResponse", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.DumpCacheResponseBody Body;
        
        public DumpCacheResponse() {
        }
        
        public DumpCacheResponse(QuickLogin.DataCenterServer.DumpCacheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class DumpCacheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuickLogin.DataCenterServer.StatusServerResult[] DumpCacheResult;
        
        public DumpCacheResponseBody() {
        }
        
        public DumpCacheResponseBody(QuickLogin.DataCenterServer.StatusServerResult[] DumpCacheResult) {
            this.DumpCacheResult = DumpCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatacenterStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatacenterStatus", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.GetDatacenterStatusRequestBody Body;
        
        public GetDatacenterStatusRequest() {
        }
        
        public GetDatacenterStatusRequest(QuickLogin.DataCenterServer.GetDatacenterStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GetDatacenterStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string game;
        
        public GetDatacenterStatusRequestBody() {
        }
        
        public GetDatacenterStatusRequestBody(string game) {
            this.game = game;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatacenterStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatacenterStatusResponse", Namespace="http://www.turbine.com/SE/GLS", Order=0)]
        public QuickLogin.DataCenterServer.GetDatacenterStatusResponseBody Body;
        
        public GetDatacenterStatusResponse() {
        }
        
        public GetDatacenterStatusResponse(QuickLogin.DataCenterServer.GetDatacenterStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GetDatacenterStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuickLogin.DataCenterServer.StatusServerResult[] GetDatacenterStatusResult;
        
        public GetDatacenterStatusResponseBody() {
        }
        
        public GetDatacenterStatusResponseBody(QuickLogin.DataCenterServer.StatusServerResult[] GetDatacenterStatusResult) {
            this.GetDatacenterStatusResult = GetDatacenterStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GLSDatacenterInfoServerSoapChannel : QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GLSDatacenterInfoServerSoapClient : System.ServiceModel.ClientBase<QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap>, QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap {
        
        public GLSDatacenterInfoServerSoapClient() {
        }
        
        public GLSDatacenterInfoServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GLSDatacenterInfoServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GLSDatacenterInfoServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GLSDatacenterInfoServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickLogin.DataCenterServer.GetDatacentersResponse QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.GetDatacenters(QuickLogin.DataCenterServer.GetDatacentersRequest request) {
            return base.Channel.GetDatacenters(request);
        }
        
        public QuickLogin.DataCenterServer.Datacenter[] GetDatacenters(string game) {
            QuickLogin.DataCenterServer.GetDatacentersRequest inValue = new QuickLogin.DataCenterServer.GetDatacentersRequest();
            inValue.Body = new QuickLogin.DataCenterServer.GetDatacentersRequestBody();
            inValue.Body.game = game;
            QuickLogin.DataCenterServer.GetDatacentersResponse retVal = ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).GetDatacenters(inValue);
            return retVal.Body.GetDatacentersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacentersResponse> QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.GetDatacentersAsync(QuickLogin.DataCenterServer.GetDatacentersRequest request) {
            return base.Channel.GetDatacentersAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacentersResponse> GetDatacentersAsync(string game) {
            QuickLogin.DataCenterServer.GetDatacentersRequest inValue = new QuickLogin.DataCenterServer.GetDatacentersRequest();
            inValue.Body = new QuickLogin.DataCenterServer.GetDatacentersRequestBody();
            inValue.Body.game = game;
            return ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).GetDatacentersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickLogin.DataCenterServer.ServerInfoResponse QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.ServerInfo(QuickLogin.DataCenterServer.ServerInfoRequest request) {
            return base.Channel.ServerInfo(request);
        }
        
        public string ServerInfo(string s) {
            QuickLogin.DataCenterServer.ServerInfoRequest inValue = new QuickLogin.DataCenterServer.ServerInfoRequest();
            inValue.Body = new QuickLogin.DataCenterServer.ServerInfoRequestBody();
            inValue.Body.s = s;
            QuickLogin.DataCenterServer.ServerInfoResponse retVal = ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).ServerInfo(inValue);
            return retVal.Body.ServerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.ServerInfoResponse> QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.ServerInfoAsync(QuickLogin.DataCenterServer.ServerInfoRequest request) {
            return base.Channel.ServerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuickLogin.DataCenterServer.ServerInfoResponse> ServerInfoAsync(string s) {
            QuickLogin.DataCenterServer.ServerInfoRequest inValue = new QuickLogin.DataCenterServer.ServerInfoRequest();
            inValue.Body = new QuickLogin.DataCenterServer.ServerInfoRequestBody();
            inValue.Body.s = s;
            return ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).ServerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickLogin.DataCenterServer.DumpCacheResponse QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.DumpCache(QuickLogin.DataCenterServer.DumpCacheRequest request) {
            return base.Channel.DumpCache(request);
        }
        
        public QuickLogin.DataCenterServer.StatusServerResult[] DumpCache() {
            QuickLogin.DataCenterServer.DumpCacheRequest inValue = new QuickLogin.DataCenterServer.DumpCacheRequest();
            inValue.Body = new QuickLogin.DataCenterServer.DumpCacheRequestBody();
            QuickLogin.DataCenterServer.DumpCacheResponse retVal = ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).DumpCache(inValue);
            return retVal.Body.DumpCacheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.DumpCacheResponse> QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.DumpCacheAsync(QuickLogin.DataCenterServer.DumpCacheRequest request) {
            return base.Channel.DumpCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuickLogin.DataCenterServer.DumpCacheResponse> DumpCacheAsync() {
            QuickLogin.DataCenterServer.DumpCacheRequest inValue = new QuickLogin.DataCenterServer.DumpCacheRequest();
            inValue.Body = new QuickLogin.DataCenterServer.DumpCacheRequestBody();
            return ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).DumpCacheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickLogin.DataCenterServer.GetDatacenterStatusResponse QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.GetDatacenterStatus(QuickLogin.DataCenterServer.GetDatacenterStatusRequest request) {
            return base.Channel.GetDatacenterStatus(request);
        }
        
        public QuickLogin.DataCenterServer.StatusServerResult[] GetDatacenterStatus(string game) {
            QuickLogin.DataCenterServer.GetDatacenterStatusRequest inValue = new QuickLogin.DataCenterServer.GetDatacenterStatusRequest();
            inValue.Body = new QuickLogin.DataCenterServer.GetDatacenterStatusRequestBody();
            inValue.Body.game = game;
            QuickLogin.DataCenterServer.GetDatacenterStatusResponse retVal = ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).GetDatacenterStatus(inValue);
            return retVal.Body.GetDatacenterStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacenterStatusResponse> QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap.GetDatacenterStatusAsync(QuickLogin.DataCenterServer.GetDatacenterStatusRequest request) {
            return base.Channel.GetDatacenterStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuickLogin.DataCenterServer.GetDatacenterStatusResponse> GetDatacenterStatusAsync(string game) {
            QuickLogin.DataCenterServer.GetDatacenterStatusRequest inValue = new QuickLogin.DataCenterServer.GetDatacenterStatusRequest();
            inValue.Body = new QuickLogin.DataCenterServer.GetDatacenterStatusRequestBody();
            inValue.Body.game = game;
            return ((QuickLogin.DataCenterServer.GLSDatacenterInfoServerSoap)(this)).GetDatacenterStatusAsync(inValue);
        }
    }
}
