//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLogin.AuthServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Global Login System Authentication ServiceSoap", Namespace="http://www.turbine.com/SE/GLS", ConfigurationName="AuthServer.GlobalLoginSystemAuthenticationServiceSoap")]
    public interface GlobalLoginSystemAuthenticationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/LoginAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QuickLogin.AuthServer.UserProfile LoginAccount(string username, string password, string additionalInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.turbine.com/SE/GLS/RefreshTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RefreshTicket(string ticket);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GameSubscription[] subscriptionsField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GameSubscription[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
                this.RaisePropertyChanged("Subscriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("Ticket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.turbine.com/SE/GLS")]
    public partial class GameSubscription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gameField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string[] productTokensField;
        
        private string[] customerServiceTokensField;
        
        private string expirationDateField;
        
        private string statusField;
        
        private string nextBillingDateField;
        
        private string pendingCancelDateField;
        
        private string autoRenewField;
        
        private string billingSystemTimeField;
        
        private string additionalInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Game {
            get {
                return this.gameField;
            }
            set {
                this.gameField = value;
                this.RaisePropertyChanged("Game");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] ProductTokens {
            get {
                return this.productTokensField;
            }
            set {
                this.productTokensField = value;
                this.RaisePropertyChanged("ProductTokens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] CustomerServiceTokens {
            get {
                return this.customerServiceTokensField;
            }
            set {
                this.customerServiceTokensField = value;
                this.RaisePropertyChanged("CustomerServiceTokens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NextBillingDate {
            get {
                return this.nextBillingDateField;
            }
            set {
                this.nextBillingDateField = value;
                this.RaisePropertyChanged("NextBillingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PendingCancelDate {
            get {
                return this.pendingCancelDateField;
            }
            set {
                this.pendingCancelDateField = value;
                this.RaisePropertyChanged("PendingCancelDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AutoRenew {
            get {
                return this.autoRenewField;
            }
            set {
                this.autoRenewField = value;
                this.RaisePropertyChanged("AutoRenew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BillingSystemTime {
            get {
                return this.billingSystemTimeField;
            }
            set {
                this.billingSystemTimeField = value;
                this.RaisePropertyChanged("BillingSystemTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("AdditionalInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalLoginSystemAuthenticationServiceSoapChannel : QuickLogin.AuthServer.GlobalLoginSystemAuthenticationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalLoginSystemAuthenticationServiceSoapClient : System.ServiceModel.ClientBase<QuickLogin.AuthServer.GlobalLoginSystemAuthenticationServiceSoap>, QuickLogin.AuthServer.GlobalLoginSystemAuthenticationServiceSoap {
        
        public GlobalLoginSystemAuthenticationServiceSoapClient() {
        }
        
        public GlobalLoginSystemAuthenticationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalLoginSystemAuthenticationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalLoginSystemAuthenticationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalLoginSystemAuthenticationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QuickLogin.AuthServer.UserProfile LoginAccount(string username, string password, string additionalInfo) {
            return base.Channel.LoginAccount(username, password, additionalInfo);
        }
        
        public string RefreshTicket(string ticket) {
            return base.Channel.RefreshTicket(ticket);
        }
    }
}
